# PCA 算法示例

In [69]:
from sklearn.decomposition import PCA

np.set_printoptions(suppress=True)
A = np.array([[3,2000],[2,3000],[4,5000],[5,8000],[1,2000]],dtype='float')
mean = np.mean(A,axis=0)# 计算每一列的均值
# 可以看到去掉均值以后方差还很大
norm = A - mean
norm
scope = np.max(norm,axis=0) - np.min(norm,axis=0)
max_min_std = norm/scope

U,S,V = np.linalg.svd(np.dot(max_min_std.T,max_min_std))
U_reduce = U[:,0].reshape(2,1)
U_reduce
R = np.dot(max_min_std,U_reduce)
R
Z = np.dot(R,U_reduce.T)
Z

array([[-0.16609096, -0.18050758],
       [-0.19766479, -0.21482201],
       [ 0.19766479,  0.21482201],
       [ 0.56142055,  0.6101516 ],
       [-0.39532959, -0.42964402]])

In [71]:
S

array([ 1.2589664 ,  0.08825582])

In [70]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

min_max_scaler = MinMaxScaler()
st =  min_max_scaler.fit_transform(A)
pca = PCA(n_components=1)
R2 = pca.fit_transform(st)
pca.inverse_transform(R2)

array([[ 0.33390904,  0.15282575],
       [ 0.30233521,  0.11851132],
       [ 0.69766479,  0.54815534],
       [ 1.06142055,  0.94348493],
       [ 0.10467041, -0.09631069]])

In [64]:
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

def std_PCA(**argv):
    scaler = MinMaxScaler()
    pca = PCA(**argv)
    pipeline = Pipeline(
        [
            ('scaler',scaler),
            ('pca',pca)
        ]
    )
    return pipeline

pca = std_PCA(n_components=1)
R2 = pca.fit_transform(A)
R2

array([[-0.2452941 ],
       [-0.29192442],
       [ 0.29192442],
       [ 0.82914294],
       [-0.58384884]])

array([[-0.2452941 ],
       [-0.29192442],
       [ 0.29192442],
       [ 0.82914294],
       [-0.58384884]])

array([[-0.2452941 ],
       [-0.29192442],
       [ 0.29192442],
       [ 0.82914294],
       [-0.58384884]])

array([[-0.2452941 ],
       [-0.29192442],
       [ 0.29192442],
       [ 0.82914294],
       [-0.58384884]])

array([-0.67710949, -0.73588229])

In [29]:
# 降维以后的数据
R

array([[ 0.2452941 ],
       [ 0.29192442],
       [-0.29192442],
       [-0.82914294],
       [ 0.58384884]])

In [31]:
# “恢复的数据”
Z

array([[-0.16609096, -0.18050758],
       [-0.19766479, -0.21482201],
       [ 0.19766479,  0.21482201],
       [ 0.56142055,  0.6101516 ],
       [-0.39532959, -0.42964402]])

In [32]:
np.multiply(Z,scope) + mean

array([[    2.33563616,  2916.95452015],
       [    2.20934082,  2711.06794139],
       [    3.79065918,  5288.93205861],
       [    5.2456822 ,  7660.90959707],
       [    1.41868164,  1422.13588278]])

使用