# 理解 PolynomialFeatures 是如何构造的 （2 阶）

使用 `sklearn.preprocessing.PolynomialFeatures` 来进行特征的构造。
它是使用多项式的方法来进行的，如果有 $a$、$b$ 两个特征，那么它的 2 次多项式的次数为 $[1, a, b, a^2, ab, b^2]$。


二阶多项式的特征集如下 $[1, a, b, a^2, ab, b^2]$。

In [1]:
X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [2]:
from sklearn.preprocessing import PolynomialFeatures

# 设置多项式阶数为２，其他的默认
# degree 多项式阶数
poly = PolynomialFeatures(degree=2)
res =  poly.fit_transform(X)
res

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

## interaction_only 的意思就是，只有相乘的项，没有平方项

+ interaction_only 设置成 True 的意思是： 例如 $[a, b]$ 的多项式交互式输出 $[1, a, b, ab]$。
+ include_bias 设置 0 次幂那一列是否要。

In [3]:
# 默认的阶数是２，同时设置交互关系为 true
poly = PolynomialFeatures(interaction_only=True, include_bias=False)
poly.fit_transform(X)

array([[ 0.,  1.,  0.],
       [ 2.,  3.,  6.],
       [ 4.,  5., 20.]])