# 交叉验证工具类

## ShuffleSplit

In [1]:
import numpy as np
from sklearn.model_selection import ShuffleSplit

X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 1, 2])

rs = ShuffleSplit(n_splits=10, test_size=.25, random_state=0)
for train_index, test_index in rs.split(X):
    print(train_index, test_index)

[3 1 0] [2]
[2 1 3] [0]
[0 2 1] [3]
[0 2 3] [1]
[2 3 0] [1]
[3 2 1] [0]
[0 2 3] [1]
[2 3 1] [0]
[3 0 1] [2]
[1 3 0] [2]


## KFold

In [2]:
from sklearn.model_selection import KFold

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [3, 4], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])
kf = KFold(n_splits=5)

In [3]:
for train_index, test_index in kf.split(X):
    print(train_index, test_index)

[2 3 4 5] [0 1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]
