# flatten 返回的是拷贝，ravel 返回的是视图

In [3]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

## 两者默认均是行序优先

In [4]:
x.flatten()

array([1, 2, 3, 4])

In [5]:
x.ravel()

array([1, 2, 3, 4])

## 拉平的时候改变顺序

In [9]:
x.flatten('F')

array([1, 3, 2, 4])

In [8]:
x.ravel('F')

array([1, 3, 2, 4])

In [11]:
x = np.array([[1, 2], [3, 4]])

In [14]:
A = x.flatten()
A[0] = 100

In [15]:
A

array([100,   2,   3,   4])

In [16]:
x

array([[1, 2],
       [3, 4]])

In [18]:
x = np.array([[1, 2], [3, 4]])
B = x.ravel()

In [19]:
B[0] = 100

In [20]:
B

array([100,   2,   3,   4])

In [21]:
x

array([[100,   2],
       [  3,   4]])