In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.ravel())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ravel(x))

[1 2 3 4 5 6]


In [4]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [5]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

In [8]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])

In [9]:
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [13]:
x = np.array([
    [[1], 
     [2], 
     [3]], 
    [[4], [5], [6]]])

In [12]:
x['b'].shape

(2, 2, 3, 3)