索引

In [1]:
import numpy as np

x = np.random.random(100000)
x

array([0.23810331, 0.42991932, 0.30456821, ..., 0.15363735, 0.52717574,
       0.35661118])

In [3]:
np.min(x)

6.8983277867751269e-07

In [4]:
np.argmin(x)

32257

In [5]:
x[32257]

6.8983277867751269e-07

In [6]:
np.max(x)

0.99999233144975819

排序和使用索引

In [7]:
x = np.arange(16)

In [8]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
# 将 x 的顺序打乱
np.random.shuffle(x)

In [10]:
x

array([ 1, 11,  8,  9,  4,  2,  0,  3, 10, 12,  7, 15,  5, 14,  6, 13])

In [11]:
# 这种方法不改变 x
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([ 1, 11,  8,  9,  4,  2,  0,  3, 10, 12,  7, 15,  5, 14,  6, 13])

In [13]:
# 下面的这行代码改变 x
x.sort()

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

对于矩阵来说

In [15]:
X = np.random.randint(10, size=(4, 4))

In [16]:
X

array([[5, 4, 9, 7],
       [4, 8, 7, 3],
       [0, 3, 2, 7],
       [5, 8, 8, 6]])

In [17]:
np.sort(X)

array([[4, 5, 7, 9],
       [3, 4, 7, 8],
       [0, 2, 3, 7],
       [5, 6, 8, 8]])

In [19]:
# 从列的方向上看是排好序的
np.sort(X,axis = 0)

array([[0, 3, 2, 3],
       [4, 4, 7, 6],
       [5, 8, 8, 7],
       [5, 8, 9, 7]])

In [21]:
# 从行的方向上看是排好序的
np.sort(X,axis = 1)

array([[4, 5, 7, 9],
       [3, 4, 7, 8],
       [0, 2, 3, 7],
       [5, 6, 8, 8]])

In [25]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
np.random.shuffle(x)

In [30]:
x

array([ 4, 13,  1,  7,  8, 14,  5,  6, 10, 11,  2, 15,  3,  0,  9, 12])

In [31]:
np.argsort(x)

array([13,  2, 10, 12,  0,  6,  7,  3,  4, 14,  8,  9, 15,  1,  5, 11])

In [32]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  5,  6, 13, 10, 11, 14, 15,  8,  7,  9, 12])

In [33]:
np.partition(x,7)

array([ 5,  4,  1,  0,  3,  2,  6,  7,  8, 12,  9, 10, 11, 13, 14, 15])

In [34]:
np.argpartition(x,3)

array([13,  2, 10, 12,  0,  6,  7,  1,  8,  9,  5, 11,  4,  3, 14, 15])

In [22]:
X

array([[5, 4, 9, 7],
       [4, 8, 7, 3],
       [0, 3, 2, 7],
       [5, 8, 8, 6]])

In [23]:
np.argsort(X,axis = 1)

array([[1, 0, 3, 2],
       [3, 0, 2, 1],
       [0, 2, 1, 3],
       [0, 3, 1, 2]])

In [24]:
np.argsort(X,axis = 0)

array([[2, 2, 2, 1],
       [1, 0, 1, 3],
       [0, 1, 3, 0],
       [3, 3, 0, 2]])

In [35]:
np.argpartition(X,2,axis=1)

array([[1, 0, 3, 2],
       [3, 0, 2, 1],
       [0, 2, 1, 3],
       [0, 3, 2, 1]])

In [36]:
np.argpartition(X,2,axis=0)

array([[2, 2, 2, 1],
       [1, 0, 1, 3],
       [0, 1, 3, 2],
       [3, 3, 0, 0]])