# 3-7 Numpy中的矩阵运算

In [3]:
n = 10

L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# 将这个列表复制两遍
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

如果我们想表示向量的数量乘法，要这样写。

In [7]:
%%time
n = 1000000
L = [i for i in range(n)]

A = []
for e in L:
    A.append(e * 2)

CPU times: user 216 ms, sys: 34.6 ms, total: 251 ms
Wall time: 249 ms


In [8]:
%%time
A = [e * 2 for e in L]

CPU times: user 67.7 ms, sys: 18.3 ms, total: 86 ms
Wall time: 84.7 ms


后者要快一些。

但是在 NumPy 中，真真实实地表现为向量的数量乘法。

In [11]:
import numpy as np

L = np.arange(n)

In [9]:
%%time
A = np.array(2 * e for e in L)

CPU times: user 9.15 ms, sys: 3.96 ms, total: 13.1 ms
Wall time: 13.1 ms


In [10]:
%%time
A = 2 * L

CPU times: user 8.72 ms, sys: 4.61 ms, total: 13.3 ms
Wall time: 13.3 ms


In [15]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [16]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [11]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [15]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [23]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [24]:
1 / X

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ],
       [ 0.09090909,  0.08333333,  0.07692308,  0.07142857,  0.06666667]])

In [25]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [27]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [28]:
np.tan(X)

array([[  1.55740772e+00,  -2.18503986e+00,  -1.42546543e-01,
          1.15782128e+00,  -3.38051501e+00],
       [ -2.91006191e-01,   8.71447983e-01,  -6.79971146e+00,
         -4.52315659e-01,   6.48360827e-01],
       [ -2.25950846e+02,  -6.35859929e-01,   4.63021133e-01,
          7.24460662e+00,  -8.55993401e-01]])

In [29]:
np.exp(X)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
          5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
          8.10308393e+03,   2.20264658e+04],
       [  5.98741417e+04,   1.62754791e+05,   4.42413392e+05,
          1.20260428e+06,   3.26901737e+06]])

下面的两个计算表达式等价。

In [31]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [33]:
3**X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [38]:
np.log(np.e**X)

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.]])

In [39]:
np.log2(2**X)

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.]])

In [41]:
np.log10(10**X)

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.]])

矩阵的运算

In [47]:
A = np.arange(4).reshape(2, 2)
A

In [17]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [51]:
# 同型矩阵对应元素相加
A + B

array([[10, 11],
       [12, 13]])

In [52]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [53]:
A * B

array([[ 0, 10],
       [20, 30]])

In [55]:
A / B

array([[ 0. ,  0.1],
       [ 0.2,  0.3]])

In [56]:
# 这才是真正的矩阵的乘法
A.dot(B)

array([[10, 10],
       [50, 50]])

In [57]:
# 矩阵的转置
A.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [42]:
v = np.array([1, 2])

In [45]:
A

array([[0, 1],
       [2, 3]])

In [46]:
v + A

array([[1, 3],
       [3, 5]])

In [59]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [60]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [62]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [63]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

## 向量和矩阵的运算

In [64]:
v

array([1, 2])

In [65]:
A

array([[0, 1],
       [2, 3]])

In [66]:
# 这不是矩阵的乘法
v * A

array([[0, 2],
       [2, 6]])

In [67]:
# 矩阵的乘法（注意，这里的向量会自动转置，以符合矩阵乘法的定义）
v.dot(A)

array([4, 7])

In [68]:
# 矩阵的乘法（注意，这里的向量会自动转置，以符合矩阵乘法的定义）
A.dot(v)

array([2, 8])

矩阵的逆

In [69]:
A

array([[0, 1],
       [2, 3]])

In [70]:
invA = np.linalg.inv(A)

In [71]:
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [72]:
A.dot(invA)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [73]:
invA.dot(A)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [75]:
X = np.arange(16).reshape((2,8))

In [76]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [77]:
pinvX = np.linalg.pinv(X)

In [78]:
pinvX

array([[ -1.35416667e-01,   5.20833333e-02],
       [ -1.01190476e-01,   4.16666667e-02],
       [ -6.69642857e-02,   3.12500000e-02],
       [ -3.27380952e-02,   2.08333333e-02],
       [  1.48809524e-03,   1.04166667e-02],
       [  3.57142857e-02,  -3.08718399e-18],
       [  6.99404762e-02,  -1.04166667e-02],
       [  1.04166667e-01,  -2.08333333e-02]])

In [81]:
X.dot(pinvX)

array([[  1.00000000e+00,  -3.05311332e-16],
       [  1.91513472e-15,   1.00000000e+00]])

In [79]:
# 广义的逆矩阵
# 矩阵的伪逆矩阵
help(np.linalg.pinv)

Help on function pinv in module numpy.linalg.linalg:

pinv(a, rcond=1e-15)
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
    
    Calculate the generalized inverse of a matrix using its
    singular-value decomposition (SVD) and including all
    *large* singular values.
    
    Parameters
    ----------
    a : (M, N) array_like
      Matrix to be pseudo-inverted.
    rcond : float
      Cutoff for small singular values.
      Singular values smaller (in modulus) than
      `rcond` * largest_singular_value (again, in modulus)
      are set to zero.
    
    Returns
    -------
    B : (N, M) ndarray
      The pseudo-inverse of `a`. If `a` is a `matrix` instance, then so
      is `B`.
    
    Raises
    ------
    LinAlgError
      If the SVD computation does not converge.
    
    Notes
    -----
    The pseudo-inverse of a matrix A, denoted :math:`A^+`, is
    defined as: "the matrix that 'solves' [the least-squares problem]
    :math:`Ax = b`," i.e., if :math:`\bar{x