# NumPy 快速预览

说明：本 notebook 参考了罗攀的书籍《从零开始学 Python 数据分析》。

In [1]:
import numpy as np

## 可以传入列表对象，也可以传入元组。

In [2]:
data1 = [5, 7, 9, 20]  # 列表
arr1 = np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [3]:
data2 = (5, 7, 9, 20)  # 元组
arr2 = np.array(data2)
arr2

array([ 5,  7,  9, 20])

In [4]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]]  # 多维数组
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 常用属性：shape 和 dtype 

In [5]:
arr3.shape

(2, 4)

In [6]:
arr3.dtype

dtype('int64')

### 只要有小数，就是 float 类型。

In [7]:
data4 = [1.2, 2, 3.45, 5]
arr4 = np.array(data4)
arr4

array([1.2 , 2.  , 3.45, 5.  ])

In [8]:
arr4.dtype

dtype('float64')

### 创建特殊的数组

In [9]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.empty((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr5 = np.ones_like(arr3)
arr5

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
arr5.dtype

dtype('int64')

In [18]:
data = [[2, 4, 5], [3, 5, 7]]
arr = np.array(data)
arr

array([[2, 4, 5],
       [3, 5, 7]])

In [19]:
arr.ndim

2

In [20]:
arr.size

6

In [21]:
arr.itemsize

8

In [22]:
arr.dtype

dtype('int64')

## NumPy 提供的数组的类型

In [23]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [24]:
arr1.dtype

dtype('int64')

In [25]:
arr2 = np.arange(5, dtype='float64')
arr2

array([0., 1., 2., 3., 4.])

In [26]:
arr2.dtype

dtype('float64')

### itemsize 属性看占用多少空间

In [27]:
arr2.itemsize

8

In [28]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [29]:
arr1.dtype

dtype('int64')

## 类型转换

In [31]:
arr2 = arr1.astype(np.float64)
arr2

array([0., 1., 2., 3., 4., 5.])

In [32]:
arr2.dtype

dtype('float64')

In [33]:
arr3 = arr1.astype('string_')
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

In [34]:
arr3.dtype

dtype('S21')

In [35]:
arr = np.array([2.3, 7.5, 5.6, 9.8])
arr

array([2.3, 7.5, 5.6, 9.8])

In [36]:
arr.astype('int32')

array([2, 7, 5, 9], dtype=int32)

In [37]:
arr.itemsize

8

In [38]:
arr1 = arr.astype('int64')

In [39]:
arr1.itemsize

8

In [40]:
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

In [41]:
arr3.astype(np.int32)

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [42]:
arr = np.array(['2', 'hello'])
arr

array(['2', 'hello'], dtype='<U5')

In [43]:
arr.astype('int32')

ValueError: invalid literal for int() with base 10: 'hello'

In [44]:
arr1 = np.arange(10)
arr1.dtype

dtype('int64')

In [45]:
arr2 = np.ones(5)
arr2.dtype

dtype('float64')

In [46]:
arr3 = arr1.astype(arr2.dtype)
arr3.dtype

dtype('float64')

In [47]:
arr = np.arange(3)
arr.dtype

dtype('int64')

In [48]:
arr.astype('float64')

array([0., 1., 2.])

In [49]:
arr

array([0, 1, 2])

## 数据重塑与合并

In [50]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
arr.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr = np.array([[3, 4, 5], [1, 2, 3]])
arr.reshape((3, 2))

array([[3, 4],
       [5, 1],
       [2, 3]])

In [53]:
arr = np.arange(12)
arr.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
arr = np.arange(10).reshape((5, 2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## ravel 与 flatten

ravel 返回的是视图；

flatten 返回的是拷贝。

In [60]:
# 返回的是视图
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
# 返回的是拷贝
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 数组的合并

In [1]:
arr1 = np.arange(12).reshape(2, 6)
arr2 = np.arange(100, 148).reshape(8, 6)

In [2]:
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [3]:
arr2

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147]])

### axis=0 表示按照行合并

**说明：压缩掉 0 轴，表示无论有多少行，都显示一行**。因此最后得到的就是有多少列。

In [4]:
result = np.concatenate([arr1, arr2], axis=0)
result

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147]])

### axis=1 表示按照列合并

In [5]:
arr1 = np.arange(0,8).reshape(4, 2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
arr2 = np.arange(100,136).reshape(4, 9)
arr2

array([[100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123, 124, 125, 126],
       [127, 128, 129, 130, 131, 132, 133, 134, 135]])

In [7]:
result = np.concatenate([arr1, arr2], axis=1)
result

array([[  0,   1, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [  2,   3, 109, 110, 111, 112, 113, 114, 115, 116, 117],
       [  4,   5, 118, 119, 120, 121, 122, 123, 124, 125, 126],
       [  6,   7, 127, 128, 129, 130, 131, 132, 133, 134, 135]])

### vertical 表示垂直

In [8]:
arr1 = np.arange(12).reshape(2, 6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [9]:
arr2 = np.arange(100, 148).reshape(8, 6)
arr2

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147]])

In [10]:
np.vstack((arr1, arr2))

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110, 111],
       [112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123],
       [124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147]])

### horizontally 表示水平

In [11]:
arr1 = np.arange(0,8).reshape(4, 2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
arr2 = np.arange(100,136).reshape(4, 9)
arr2

array([[100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117],
       [118, 119, 120, 121, 122, 123, 124, 125, 126],
       [127, 128, 129, 130, 131, 132, 133, 134, 135]])

In [13]:
np.hstack((arr1, arr2))

array([[  0,   1, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [  2,   3, 109, 110, 111, 112, 113, 114, 115, 116, 117],
       [  4,   5, 118, 119, 120, 121, 122, 123, 124, 125, 126],
       [  6,   7, 127, 128, 129, 130, 131, 132, 133, 134, 135]])

## 数组的拆分

In [15]:
arr = np.arange(12).reshape((6, 2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
# 表示在索引之前拆分
result = np.split(arr, [1, 2, 4])

for item in result:
    print(item, end='\n\n')

[[0 1]]

[[2 3]]

[[4 5]
 [6 7]]

[[ 8  9]
 [10 11]]



### 转置

In [18]:
arr = np.arange(12).reshape(2, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
arr.transpose((1, 0))

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [20]:
arr.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

## 交换通道

In [21]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [22]:
print(arr.shape)

(2, 2, 4)


In [23]:
result = arr.swapaxes(1, 2)
print(result.shape)

(2, 4, 2)


# 随机数

In [98]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[188, 155, 166, 192],
       [155, 135, 136, 180],
       [137, 130, 136, 172],
       [128, 132, 106, 146],
       [156, 100, 134, 161]])

In [100]:
arr = np.random.randn(2, 3, 5)
arr.shape

(2, 3, 5)

In [102]:
arr = np.random.normal(4, 5, size=(3, 5))
arr.shape

(3, 5)

In [104]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[183, 167, 190, 155],
       [177, 115, 103, 111],
       [114, 104, 168, 143],
       [171, 105, 130, 191],
       [157, 161, 196, 160]])

In [105]:
np.random.permutation(arr)

array([[157, 161, 196, 160],
       [114, 104, 168, 143],
       [177, 115, 103, 111],
       [183, 167, 190, 155],
       [171, 105, 130, 191]])

In [106]:
arr

array([[183, 167, 190, 155],
       [177, 115, 103, 111],
       [114, 104, 168, 143],
       [171, 105, 130, 191],
       [157, 161, 196, 160]])

## permutation 返回新的数组，shuffle 是原地修改

In [109]:
lst = np.arange(10)
lst
# 返回新的数组，不是原地修改
np.random.permutation(lst)

array([0, 8, 4, 9, 5, 3, 1, 7, 2, 6])

In [110]:
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
lst = np.arange(10)
lst

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.random.shuffle(lst)

In [113]:
lst

array([7, 6, 0, 3, 2, 5, 9, 1, 8, 4])

In [92]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[196, 140, 199, 182],
       [161, 109, 193, 176],
       [102, 138, 165, 166],
       [191, 181, 108, 113],
       [168, 102, 199, 150]])

In [93]:
np.random.shuffle(arr)

In [94]:
arr

array([[168, 102, 199, 150],
       [191, 181, 108, 113],
       [102, 138, 165, 166],
       [161, 109, 193, 176],
       [196, 140, 199, 182]])

## 索引和切片

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[3]

3

In [17]:
arr[-1]

9

In [18]:
arr[2] = 123
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [19]:
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [20]:
arr[3] = 88
arr

array([  0,   1, 123,  88,   4,   5,   6,   7,   8,   9])

In [22]:
arr1 = arr[-3:-1]
arr1

array([7, 8])

### NumPy 的索引为了节约空间，与原始数组共享，即切片全部是视图

In [23]:
arr1[:] = 77
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [24]:
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [26]:
arr1 = arr[1].copy()
arr1 = 34
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [27]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr[0]

array([0, 1, 2, 3, 4])

In [29]:
arr[2]

array([10, 11, 12, 13, 14])

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 索引到一个具体的矩阵元素

In [31]:
arr[0][3]

3

In [32]:
arr[2, 3]  # 两种方法等价

13

In [33]:
arr = np.arange(12).reshape(2, 2, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

### 切片全部是视图

In [35]:
old = arr[0].copy()
arr[0] = 12
arr

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
arr[0] = old
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [37]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [38]:
arr[1, 1]

array([ 9, 10, 11])

In [39]:
arr[0, 1, 2]

5

In [40]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[2:5]

array([2, 3, 4])

In [42]:
arr = np.arange(12).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
arr[:, 1]

array([ 1,  4,  7, 10])

In [47]:
arr[:, 1:2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [49]:
arr[2:, 1:]

array([[ 7,  8],
       [10, 11]])

In [59]:
fruits = np.array(['apple', 'banana', 'pear',
                   'banana', 'pear', 'apple', 'pear'])
datas = np.random.randint(-1, 1, size=(7, 5))

## 花式索引

In [60]:
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [61]:
datas

array([[ 0, -1,  0,  0, -1],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, -1,  0, -1],
       [ 0, -1,  0, -1,  0],
       [-1, -1,  0, -1, -1],
       [-1, -1, -1, -1,  0],
       [ 0,  0, -1, -1,  0]])

In [59]:
fruits == 'pear'

array([False, False,  True, False,  True, False,  True], dtype=bool)

In [60]:
datas[fruits == 'pear']

array([[-1,  0, -1, -1,  0],
       [ 0,  0,  0,  0, -1],
       [ 0,  0, -1,  0, -1]])

In [61]:
datas[fruits != 'pear']

array([[ 0, -1,  0,  0, -1],
       [-1, -1,  0,  0, -1],
       [-1,  0,  0, -1,  0],
       [-1, -1,  0,  0,  0]])

In [62]:
datas[(fruits == 'apple') | (fruits == 'banana')]

array([[ 0, -1,  0,  0, -1],
       [-1, -1,  0,  0, -1],
       [-1,  0,  0, -1,  0],
       [-1, -1,  0,  0,  0]])

In [63]:
datas[fruits == 'pear', 2:]

array([[-1, -1,  0],
       [ 0,  0, -1],
       [-1,  0, -1]])

In [64]:
datas[fruits == 'pear', 2]

array([-1,  0, -1])

In [66]:
datas[datas == 0] = 1
datas

array([[ 1, -1,  1,  1, -1],
       [-1, -1,  1,  1, -1],
       [-1,  1, -1, -1,  1],
       [-1,  1,  1, -1,  1],
       [ 1,  1,  1,  1, -1],
       [-1, -1,  1,  1,  1],
       [ 1,  1, -1,  1, -1]])

In [67]:
arr = np.arange(12).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
arr[[1, 3, 2]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [70]:
arr[[3, 2]][:, [2, 1]]

array([[11, 10],
       [ 8,  7]])

In [71]:
arr[np.ix_([3, 2], [2, 1])]

array([[11, 10],
       [ 8,  7]])

In [72]:
a = [1, 2, 3]
b = []
for i in a:
    b.append(i * 10)
b

[10, 20, 30]

In [73]:
arr = np.array([1, 2, 3])
arr * 10

array([10, 20, 30])

In [74]:
arr * arr

array([1, 4, 9])

In [75]:
arr - arr

array([0, 0, 0])

In [77]:
arr = np.random.randn(3, 3)
arr

array([[-1.30289625, -1.62082859, -0.02086977],
       [ 0.61681656,  1.44215576,  1.7281482 ],
       [-0.96761142,  0.6475979 , -0.57524988]])

In [78]:
np.abs(arr)

array([[ 1.30289625,  1.62082859,  0.02086977],
       [ 0.61681656,  1.44215576,  1.7281482 ],
       [ 0.96761142,  0.6475979 ,  0.57524988]])

In [79]:
np.square(arr)

array([[  1.69753863e+00,   2.62708531e+00,   4.35547217e-04],
       [  3.80462668e-01,   2.07981323e+00,   2.98649619e+00],
       [  9.36271853e-01,   4.19383043e-01,   3.30912420e-01]])

In [82]:
arr1 = np.random.randint(1, 10, size=(5))
arr1

array([5, 2, 9, 4, 1])

In [83]:
arr2 = np.random.randint(1, 10, size=(5))
arr2

array([7, 6, 9, 1, 3])

In [84]:
np.add(arr1, arr2)

array([12,  8, 18,  5,  4])

In [85]:
np.minimum(arr1, arr2)

array([5, 2, 9, 1, 1])

In [86]:
arr = np.random.normal(2, 4, size=(6,))
arr

array([ 4.03156633,  2.24471147, -1.05295999,  3.17361538,  9.45900887,
        2.48014303])

In [87]:
np.modf(arr)

(array([ 0.03156633,  0.24471147, -0.05295999,  0.17361538,  0.45900887,
         0.48014303]), array([ 4.,  2., -1.,  3.,  9.,  2.]))

## where 的用法

In [88]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
cond = np.array([True, False, False, True])

In [89]:
result = [(x if c else y) for x, y, c in zip(arr1, arr2, cond)]
result

[1, 6, 7, 4]

In [91]:
result = np.where(cond, arr1, arr2)
result

array([1, 6, 7, 4])

In [93]:
arr = np.random.randn(4, 4)
arr

array([[ 0.99483299, -0.42559031,  0.60728194, -0.28477079],
       [-0.47341549, -1.03284446, -1.24692688, -0.7168212 ],
       [-0.2463296 ,  0.9006737 , -0.8362647 ,  0.28860023],
       [ 0.24025673, -1.14644973,  0.84133157, -0.00742223]])

In [94]:
new_arr = np.where(arr > 0, 1, -1)
new_arr

array([[ 1, -1,  1, -1],
       [-1, -1, -1, -1],
       [-1,  1, -1,  1],
       [ 1, -1,  1, -1]])

In [115]:
arr = np.random.randint(1, 300, size=(3, 3))
arr

array([[177, 177,  99],
       [238, 233, 131],
       [125, 288,   5]])

### 嵌套的 where 的用法

In [116]:
new_arr = np.where(arr > 200, 3,
                   np.where(arr > 100, 2, 1))
new_arr

array([[2, 2, 1],
       [3, 3, 2],
       [2, 3, 1]])

## 汇总函数

In [24]:
arr = np.random.randn(2, 4)
arr

array([[-1.45281262, -0.64047122,  0.09231784,  0.47471484],
       [ 0.93289249,  0.36737676,  0.7705826 , -0.88178549]])

In [25]:
arr.sum()

-0.3371848106842392

In [26]:
arr.mean()

-0.0421481013355299

In [27]:
arr.std()

0.7997757683865745

In [28]:
arr

array([[-1.45281262, -0.64047122,  0.09231784,  0.47471484],
       [ 0.93289249,  0.36737676,  0.7705826 , -0.88178549]])

## axis = 1 表示压缩掉列，即无论你有多少列，你都只看到行数不变的数据，压缩的方式，就是指指定的方法

In [29]:
arr

array([[-1.45281262, -0.64047122,  0.09231784,  0.47471484],
       [ 0.93289249,  0.36737676,  0.7705826 , -0.88178549]])

In [30]:
arr.mean(axis=1)

array([-0.38156279,  0.29726659])

In [31]:
arr.sum(axis=0)

array([-0.51992013, -0.27309446,  0.86290044, -0.40707066])

In [125]:
arr = np.arange(12).reshape(2, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [126]:
arr.cumsum(0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16]])

In [127]:
arr.cumprod(1)

array([[     0,      0,      0,      0,      0,      0],
       [     6,     42,    336,   3024,  30240, 332640]])

In [132]:
arr = np.random.randn(20)
arr

array([ 0.64854453, -1.02444099,  1.18506546,  1.0588872 , -1.67297679,
        1.11245385, -1.47720606,  0.67531455,  0.10707936,  1.60181681,
       -0.09663766,  0.13821122,  2.08949018, -0.85208144, -1.01504574,
       -1.01749498,  0.42782922, -0.83512655,  0.20623175, -0.23411408])

In [128]:
(arr > 0).sum()

11

In [129]:
arr = np.array([True, False, False, True])
arr

array([ True, False, False,  True])

In [130]:
arr.any()

True

In [131]:
arr.all()

False

In [149]:
arr = np.random.randint(100, 1000, 10)
arr

array([910, 265, 410, 195, 102, 603, 286, 667, 262, 571])

In [150]:
arr.sort()
arr

array([102, 195, 262, 265, 286, 410, 571, 603, 667, 910])

array([[5, 7, 3, 2, 3, 6, 6, 2],
       [4, 1, 2, 2, 9, 9, 1, 6],
       [7, 2, 2, 1, 4, 1, 2, 9],
       [9, 6, 6, 9, 8, 3, 8, 5]])

## arr.sort(axis=0) 表示在列的方向上进行排序

In [162]:
arr = np.random.randint(1, 10, (4, 8))
arr

array([[5, 5, 7, 7, 2, 8, 6, 2],
       [9, 7, 1, 6, 9, 8, 9, 6],
       [7, 7, 9, 9, 2, 3, 3, 4],
       [7, 9, 2, 4, 3, 9, 5, 6]])

In [163]:
arr.sort(axis=0)
arr

array([[5, 5, 1, 4, 2, 3, 3, 2],
       [7, 7, 2, 6, 2, 8, 5, 4],
       [7, 7, 7, 7, 3, 8, 6, 6],
       [9, 9, 9, 9, 9, 9, 9, 6]])

## arr.sort(axis=1) 表示在行的方向上进行排序

In [165]:
arr = np.random.randint(1, 10, (4, 8))
arr

array([[1, 1, 9, 6, 3, 8, 6, 2],
       [8, 8, 6, 4, 5, 3, 6, 7],
       [4, 8, 3, 9, 6, 9, 7, 1],
       [2, 4, 7, 3, 6, 4, 5, 9]])

In [167]:
arr.sort(axis=1)
arr

array([[1, 1, 2, 3, 6, 6, 8, 9],
       [3, 4, 5, 6, 6, 7, 8, 8],
       [1, 3, 4, 6, 7, 8, 9, 9],
       [2, 3, 4, 4, 5, 6, 7, 9]])

In [132]:
arr = np.random.randn(10)
arr

array([-0.35069747, -0.72696133, -0.42587341, -0.95635282,  0.65643218,
        1.08189221, -0.01741093,  2.47765718,  0.99202566, -0.75222115])

In [133]:
arr.sort()
arr

array([-0.95635282, -0.75222115, -0.72696133, -0.42587341, -0.35069747,
       -0.01741093,  0.65643218,  0.99202566,  1.08189221,  2.47765718])

In [140]:
arr = np.random.randn(5, 3)
arr

array([[ 0.76464658,  1.03958729,  0.83151511],
       [ 1.63188956, -0.62708685,  0.05175314],
       [ 0.85665906, -0.24305887,  1.30020042],
       [ 2.00108815, -1.49244044, -0.06771401],
       [ 0.26482398, -1.42061605, -1.0372988 ]])

In [141]:
arr.sort(1)
arr

array([[ 0.76464658,  0.83151511,  1.03958729],
       [-0.62708685,  0.05175314,  1.63188956],
       [-0.24305887,  0.85665906,  1.30020042],
       [-1.49244044, -0.06771401,  2.00108815],
       [-1.42061605, -1.0372988 ,  0.26482398]])

In [142]:
fruits = np.array(['apple', 'banana', 'pear',
                   'banana', 'pear', 'apple', 'pear'])
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [144]:
np.unique(fruits)

array(['apple', 'banana', 'pear'],
      dtype='<U6')

In [145]:
arr = np.array([2, 3, 3, 2, 8, 1])
arr

array([2, 3, 3, 2, 8, 1])

In [146]:
np.unique(arr)

array([1, 2, 3, 8])

In [147]:
arr = np.array([2, 3, 5, 7])
arr

array([2, 3, 5, 7])

In [148]:
np.in1d(arr, [2, 7])

array([ True, False, False,  True], dtype=bool)

In [149]:
arr = np.arange(12).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [152]:
np.savetxt('ch2ex1.csv', arr, fmt='%d', delimiter=',')

In [153]:
!type ch2ex1.csv

0,1,2
3,4,5
6,7,8
9,10,11


In [155]:
arr = np.loadtxt('ch2ex1.csv', delimiter=',')
arr

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [156]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
arr2 = np.arange(9).reshape(3, 3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [159]:
np.dot(arr1, arr2)

array([[24, 30, 36],
       [51, 66, 81]])

In [160]:
from numpy.linalg import det

In [161]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [162]:
det(arr)

-2.0000000000000004

# 图像处理

In [63]:
from PIL import Image
import numpy as np

In [64]:
im = np.array(Image.open('hua.jpeg'))
print(im.shape, im.dtype)

(1200, 1920, 3) uint8


In [65]:
im

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [108,  98,  13],
        [108,  98,  13],
        [107,  97,  12]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [108,  98,  13],
        [108,  98,  13],
        [105,  97,  12]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [106,  98,  13],
        [106,  98,  13],
        [105,  97,  12]],

       ...,

       [[247, 211, 215],
        [247, 211, 215],
        [247, 211, 215],
        ...,
        [146, 153, 119],
        [149, 156, 122],
        [144, 151, 117]],

       [[247, 211, 215],
        [247, 211, 215],
        [247, 211, 215],
        ...,
        [143, 150, 117],
        [142, 149, 116],
        [141, 148, 115]],

       [[247, 211, 215],
        [247, 211, 215],
        [246, 210, 214],
        ...,
        [148, 155, 122],
        [134, 141, 108],
        [128, 135, 102]]

In [68]:
# 这里用到了广播
b = [255, 255, 255] - im    #数组运算
new_im = Image.fromarray(b.astype('uint8'))  
new_im.save('hua1.jpeg')  #保存为新图像

In [67]:
b

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [147, 157, 242],
        [147, 157, 242],
        [148, 158, 243]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [147, 157, 242],
        [147, 157, 242],
        [150, 158, 243]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [149, 157, 242],
        [149, 157, 242],
        [150, 158, 243]],

       ...,

       [[  8,  44,  40],
        [  8,  44,  40],
        [  8,  44,  40],
        ...,
        [109, 102, 136],
        [106,  99, 133],
        [111, 104, 138]],

       [[  8,  44,  40],
        [  8,  44,  40],
        [  8,  44,  40],
        ...,
        [112, 105, 138],
        [113, 106, 139],
        [114, 107, 140]],

       [[  8,  44,  40],
        [  8,  44,  40],
        [  9,  45,  41],
        ...,
        [107, 100, 133],
        [121, 114, 147],
        [127, 120, 153]]