In [1]:
import numpy as np
a = np.arange(10, 25, dtype=float)
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24.])

### 默认情况下可以重复抽取，即 replace 的值为 True

In [2]:
np.random.choice(a, size=(4, 3))

array([[21., 14., 22.],
       [17., 19., 23.],
       [15., 19., 24.],
       [19., 12., 22.]])

可以看到，会抽到重复的。

### 不重复抽取

In [6]:
np.random.choice(a, size=(4, 3), replace=False)

array([[18., 15., 17.],
       [10., 16., 14.],
       [19., 23., 21.],
       [20., 24., 22.]])

可以看到不会抽到重复的，因此候选的数一定要够用。

### 设置随机数种子

In [8]:
np.random.seed(42)
np.random.randint(0, 100, 3)

array([51, 92, 14])

In [10]:
np.random.randint(0, 100, 3)

array([71, 60, 20])

In [11]:
np.random.seed(42)
np.random.randint(0, 100, 3)

array([51, 92, 14])

In [12]:
np.random.randint(0, 100, 3)

array([71, 60, 20])