正态分布：期望值和标准差。

均匀分布：区间的起始值、终值。

poisson：泊松分布，系数表示单位时间（或单位面积）内随机事件的平均发生率。由于泊松分布是一个离散分布，因此它输出的数组是一个整数数组。


In [1]:
import numpy as np

In [3]:
np.random.normal(100, 10, size=(4, 3))

array([[ 94.17471305, 105.17097948, 106.2922715 ],
       [120.61556112, 100.86919235, 110.98478645],
       [ 98.36833193,  89.87487177,  89.82889041],
       [ 98.42387346, 109.30888399, 100.30190553]])

In [4]:
np.random.uniform(10, 20, (4, 3))

array([[16.49832988, 16.83236151, 13.41854631],
       [19.221797  , 14.16411956, 16.27731926],
       [19.55210237, 16.85870515, 14.6704787 ],
       [18.11165972, 14.66860717, 17.48103126]])

In [5]:
np.random.poisson(2.0, (4, 3))

array([[5, 1, 1],
       [4, 2, 2],
       [2, 2, 1],
       [6, 1, 2]])

In [7]:
a = np.array([1,10,20,30,40])
np.random.permutation(a)

array([30, 20, 40, 10,  1])

In [8]:
np.random.permutation(10)

array([3, 4, 6, 2, 0, 5, 8, 9, 1, 7])

### permutation 与 shuffle 的区别

permutation：置换，返回一个新的数组。

shuffle：洗牌，直接将参数数组的顺序打乱。